
name: CI-CD

on:
  push:
    branches: [ master , CoreSource ]
  pull_request:
    branches: [ master , CoreSource ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: ls

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
