
name: CI-CD

on:
  push:
    branches: [ master , CoreSource ]
  pull_request:
    branches: [ master , CoreSource ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: |
          git fetch
          git checkout CoreSource
          ls
          npm install
          npm run build
          git config --global user.name 'CI_CD Agent'
          git config --global user.email 'skawle631@gmail.com'
          git add -A
          git commit -am "Automated PUBLISH [SUCCESS] -> CoreSource"
          ls

      - name: Copy buld to master branch
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
